package com.ontheroad.dao;

import com.ontheroad.entity.equipmentDatatype;
import com.ontheroad.entity.equipmentDatatypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface equipmentDatatypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    long countByExample(equipmentDatatypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    int deleteByExample(equipmentDatatypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    int deleteByPrimaryKey(Integer equipmentType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    int insert(equipmentDatatype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    int insertSelective(equipmentDatatype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    List<equipmentDatatype> selectByExample(equipmentDatatypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    equipmentDatatype selectByPrimaryKey(Integer equipmentType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") equipmentDatatype record, @Param("example") equipmentDatatypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    int updateByExample(@Param("record") equipmentDatatype record, @Param("example") equipmentDatatypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    int updateByPrimaryKeySelective(equipmentDatatype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_datatype
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    int updateByPrimaryKey(equipmentDatatype record);
}