package com.ontheroad.dao;

import com.ontheroad.entity.FirmVersion;
import com.ontheroad.entity.FirmVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirmVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    int countByExample(FirmVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    int deleteByExample(FirmVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    int insert(FirmVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    int insertSelective(FirmVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    List<FirmVersion> selectByExample(FirmVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    FirmVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") FirmVersion record, @Param("example") FirmVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    int updateByExample(@Param("record") FirmVersion record, @Param("example") FirmVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    int updateByPrimaryKeySelective(FirmVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    int updateByPrimaryKey(FirmVersion record);
}