package com.ontheroad.dao;

import com.ontheroad.entity.Lunbo;
import com.ontheroad.entity.LunboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LunboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int countByExample(LunboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int deleteByExample(LunboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int insert(Lunbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int insertSelective(Lunbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    List<Lunbo> selectByExampleWithBLOBs(LunboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    List<Lunbo> selectByExample(LunboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    Lunbo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") Lunbo record, @Param("example") LunboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Lunbo record, @Param("example") LunboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int updateByExample(@Param("record") Lunbo record, @Param("example") LunboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Lunbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int updateByPrimaryKeyWithBLOBs(Lunbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    int updateByPrimaryKey(Lunbo record);
}