package com.ontheroad.dao;

import com.ontheroad.entity.TbEquipment;
import com.ontheroad.entity.TbEquipmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbEquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    int countByExample(TbEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    int deleteByExample(TbEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer equipmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    int insert(TbEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    int insertSelective(TbEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    List<TbEquipment> selectByExample(TbEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    TbEquipment selectByPrimaryKey(Integer equipmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TbEquipment record, @Param("example") TbEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TbEquipment record, @Param("example") TbEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TbEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    int updateByPrimaryKey(TbEquipment record);
}