package com.ontheroad.mysql.entity;

import java.util.Date;

public class TbEquipmentstatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.status_id
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private Integer statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.equipment_id
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private Integer equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.workStatus
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private String workstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.voicebroadcast
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private String voicebroadcast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.volume
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private String volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.temperature
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private String temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.backlight
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private String backlight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.ip
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.port
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private String port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.last_active_at
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private Date lastActiveAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipmentstatus.firmware_version
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    private String firmwareVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.status_id
     *
     * @return the value of tb_equipmentstatus.status_id
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.status_id
     *
     * @param statusId the value for tb_equipmentstatus.status_id
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.equipment_id
     *
     * @return the value of tb_equipmentstatus.equipment_id
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public Integer getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.equipment_id
     *
     * @param equipmentId the value for tb_equipmentstatus.equipment_id
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setEquipmentId(Integer equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.workStatus
     *
     * @return the value of tb_equipmentstatus.workStatus
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public String getWorkstatus() {
        return workstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.workStatus
     *
     * @param workstatus the value for tb_equipmentstatus.workStatus
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setWorkstatus(String workstatus) {
        this.workstatus = workstatus == null ? null : workstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.voicebroadcast
     *
     * @return the value of tb_equipmentstatus.voicebroadcast
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public String getVoicebroadcast() {
        return voicebroadcast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.voicebroadcast
     *
     * @param voicebroadcast the value for tb_equipmentstatus.voicebroadcast
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setVoicebroadcast(String voicebroadcast) {
        this.voicebroadcast = voicebroadcast == null ? null : voicebroadcast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.volume
     *
     * @return the value of tb_equipmentstatus.volume
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.volume
     *
     * @param volume the value for tb_equipmentstatus.volume
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.temperature
     *
     * @return the value of tb_equipmentstatus.temperature
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.temperature
     *
     * @param temperature the value for tb_equipmentstatus.temperature
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.backlight
     *
     * @return the value of tb_equipmentstatus.backlight
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public String getBacklight() {
        return backlight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.backlight
     *
     * @param backlight the value for tb_equipmentstatus.backlight
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setBacklight(String backlight) {
        this.backlight = backlight == null ? null : backlight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.ip
     *
     * @return the value of tb_equipmentstatus.ip
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.ip
     *
     * @param ip the value for tb_equipmentstatus.ip
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.port
     *
     * @return the value of tb_equipmentstatus.port
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.port
     *
     * @param port the value for tb_equipmentstatus.port
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.last_active_at
     *
     * @return the value of tb_equipmentstatus.last_active_at
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public Date getLastActiveAt() {
        return lastActiveAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.last_active_at
     *
     * @param lastActiveAt the value for tb_equipmentstatus.last_active_at
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setLastActiveAt(Date lastActiveAt) {
        this.lastActiveAt = lastActiveAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipmentstatus.firmware_version
     *
     * @return the value of tb_equipmentstatus.firmware_version
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public String getFirmwareVersion() {
        return firmwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipmentstatus.firmware_version
     *
     * @param firmwareVersion the value for tb_equipmentstatus.firmware_version
     *
     * @mbggenerated Thu Oct 19 16:15:34 CST 2017
     */
    public void setFirmwareVersion(String firmwareVersion) {
        this.firmwareVersion = firmwareVersion == null ? null : firmwareVersion.trim();
    }
}