package com.ontheroad.entity;

public class equipmentDatatype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_datatype.equipment_type
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    private Integer equipmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_datatype.equipment_name
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    private String equipmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_datatype.period
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    private Integer period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_datatype.remark
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_datatype.product_name
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    private String productName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_datatype.equipment_type
     *
     * @return the value of equipment_datatype.equipment_type
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    public Integer getEquipmentType() {
        return equipmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_datatype.equipment_type
     *
     * @param equipmentType the value for equipment_datatype.equipment_type
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    public void setEquipmentType(Integer equipmentType) {
        this.equipmentType = equipmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_datatype.equipment_name
     *
     * @return the value of equipment_datatype.equipment_name
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_datatype.equipment_name
     *
     * @param equipmentName the value for equipment_datatype.equipment_name
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName == null ? null : equipmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_datatype.period
     *
     * @return the value of equipment_datatype.period
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_datatype.period
     *
     * @param period the value for equipment_datatype.period
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_datatype.remark
     *
     * @return the value of equipment_datatype.remark
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_datatype.remark
     *
     * @param remark the value for equipment_datatype.remark
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_datatype.product_name
     *
     * @return the value of equipment_datatype.product_name
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_datatype.product_name
     *
     * @param productName the value for equipment_datatype.product_name
     *
     * @mbg.generated Fri Oct 06 20:11:00 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }
}