package com.ontheroad.entity;

public class FirmVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_version.id
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_version.product
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    private String product;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_version.type
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_version.version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_version.firm_url
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    private String firmUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_version.remark
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_version.id
     *
     * @return the value of firm_version.id
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_version.id
     *
     * @param id the value for firm_version.id
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_version.product
     *
     * @return the value of firm_version.product
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_version.product
     *
     * @param product the value for firm_version.product
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_version.type
     *
     * @return the value of firm_version.type
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_version.type
     *
     * @param type the value for firm_version.type
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_version.version
     *
     * @return the value of firm_version.version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_version.version
     *
     * @param version the value for firm_version.version
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_version.firm_url
     *
     * @return the value of firm_version.firm_url
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public String getFirmUrl() {
        return firmUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_version.firm_url
     *
     * @param firmUrl the value for firm_version.firm_url
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public void setFirmUrl(String firmUrl) {
        this.firmUrl = firmUrl == null ? null : firmUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_version.remark
     *
     * @return the value of firm_version.remark
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_version.remark
     *
     * @param remark the value for firm_version.remark
     *
     * @mbggenerated Wed Oct 11 15:21:09 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}