package com.ontheroad.entity;

import java.util.Date;

public class Lunbo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo.id
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo.title
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo.lunbo_order
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    private Long lunboOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo.is_show
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    private Integer isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo.s_img
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    private String sImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo.ctime
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo.content
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo.id
     *
     * @return the value of lunbo.id
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo.id
     *
     * @param id the value for lunbo.id
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo.title
     *
     * @return the value of lunbo.title
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo.title
     *
     * @param title the value for lunbo.title
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo.lunbo_order
     *
     * @return the value of lunbo.lunbo_order
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public Long getLunboOrder() {
        return lunboOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo.lunbo_order
     *
     * @param lunboOrder the value for lunbo.lunbo_order
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public void setLunboOrder(Long lunboOrder) {
        this.lunboOrder = lunboOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo.is_show
     *
     * @return the value of lunbo.is_show
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo.is_show
     *
     * @param isShow the value for lunbo.is_show
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo.s_img
     *
     * @return the value of lunbo.s_img
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public String getsImg() {
        return sImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo.s_img
     *
     * @param sImg the value for lunbo.s_img
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public void setsImg(String sImg) {
        this.sImg = sImg == null ? null : sImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo.ctime
     *
     * @return the value of lunbo.ctime
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo.ctime
     *
     * @param ctime the value for lunbo.ctime
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo.content
     *
     * @return the value of lunbo.content
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo.content
     *
     * @param content the value for lunbo.content
     *
     * @mbggenerated Sun Oct 15 19:05:11 GMT+08:00 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}