package com.ontheroad.entity;

import java.util.Date;

public class TbEquipment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipment.equipment_id
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    private Integer equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipment.user_id
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipment.equipmentNum
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    private String equipmentnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipment.type
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipment.equipmentPicture
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    private String equipmentpicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipment.equipmentName
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    private String equipmentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipment.created_at
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipment.binded_at
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    private Date bindedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_equipment.product
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    private String product;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipment.equipment_id
     *
     * @return the value of tb_equipment.equipment_id
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public Integer getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipment.equipment_id
     *
     * @param equipmentId the value for tb_equipment.equipment_id
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setEquipmentId(Integer equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipment.user_id
     *
     * @return the value of tb_equipment.user_id
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipment.user_id
     *
     * @param userId the value for tb_equipment.user_id
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipment.equipmentNum
     *
     * @return the value of tb_equipment.equipmentNum
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public String getEquipmentnum() {
        return equipmentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipment.equipmentNum
     *
     * @param equipmentnum the value for tb_equipment.equipmentNum
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setEquipmentnum(String equipmentnum) {
        this.equipmentnum = equipmentnum == null ? null : equipmentnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipment.type
     *
     * @return the value of tb_equipment.type
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipment.type
     *
     * @param type the value for tb_equipment.type
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipment.equipmentPicture
     *
     * @return the value of tb_equipment.equipmentPicture
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public String getEquipmentpicture() {
        return equipmentpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipment.equipmentPicture
     *
     * @param equipmentpicture the value for tb_equipment.equipmentPicture
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setEquipmentpicture(String equipmentpicture) {
        this.equipmentpicture = equipmentpicture == null ? null : equipmentpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipment.equipmentName
     *
     * @return the value of tb_equipment.equipmentName
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public String getEquipmentname() {
        return equipmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipment.equipmentName
     *
     * @param equipmentname the value for tb_equipment.equipmentName
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setEquipmentname(String equipmentname) {
        this.equipmentname = equipmentname == null ? null : equipmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipment.created_at
     *
     * @return the value of tb_equipment.created_at
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipment.created_at
     *
     * @param createdAt the value for tb_equipment.created_at
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipment.binded_at
     *
     * @return the value of tb_equipment.binded_at
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public Date getBindedAt() {
        return bindedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipment.binded_at
     *
     * @param bindedAt the value for tb_equipment.binded_at
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setBindedAt(Date bindedAt) {
        this.bindedAt = bindedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_equipment.product
     *
     * @return the value of tb_equipment.product
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_equipment.product
     *
     * @param product the value for tb_equipment.product
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }
}