package com.ontheroad.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbEquipmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public TbEquipmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEquipmentIdIsNull() {
            addCriterion("equipment_id is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIsNotNull() {
            addCriterion("equipment_id is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdEqualTo(Integer value) {
            addCriterion("equipment_id =", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotEqualTo(Integer value) {
            addCriterion("equipment_id <>", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThan(Integer value) {
            addCriterion("equipment_id >", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("equipment_id >=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThan(Integer value) {
            addCriterion("equipment_id <", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThanOrEqualTo(Integer value) {
            addCriterion("equipment_id <=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIn(List<Integer> values) {
            addCriterion("equipment_id in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotIn(List<Integer> values) {
            addCriterion("equipment_id not in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdBetween(Integer value1, Integer value2) {
            addCriterion("equipment_id between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("equipment_id not between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumIsNull() {
            addCriterion("equipmentNum is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumIsNotNull() {
            addCriterion("equipmentNum is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumEqualTo(String value) {
            addCriterion("equipmentNum =", value, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumNotEqualTo(String value) {
            addCriterion("equipmentNum <>", value, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumGreaterThan(String value) {
            addCriterion("equipmentNum >", value, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumGreaterThanOrEqualTo(String value) {
            addCriterion("equipmentNum >=", value, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumLessThan(String value) {
            addCriterion("equipmentNum <", value, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumLessThanOrEqualTo(String value) {
            addCriterion("equipmentNum <=", value, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumLike(String value) {
            addCriterion("equipmentNum like", value, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumNotLike(String value) {
            addCriterion("equipmentNum not like", value, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumIn(List<String> values) {
            addCriterion("equipmentNum in", values, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumNotIn(List<String> values) {
            addCriterion("equipmentNum not in", values, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumBetween(String value1, String value2) {
            addCriterion("equipmentNum between", value1, value2, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumNotBetween(String value1, String value2) {
            addCriterion("equipmentNum not between", value1, value2, "equipmentnum");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureIsNull() {
            addCriterion("equipmentPicture is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureIsNotNull() {
            addCriterion("equipmentPicture is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureEqualTo(String value) {
            addCriterion("equipmentPicture =", value, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureNotEqualTo(String value) {
            addCriterion("equipmentPicture <>", value, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureGreaterThan(String value) {
            addCriterion("equipmentPicture >", value, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureGreaterThanOrEqualTo(String value) {
            addCriterion("equipmentPicture >=", value, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureLessThan(String value) {
            addCriterion("equipmentPicture <", value, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureLessThanOrEqualTo(String value) {
            addCriterion("equipmentPicture <=", value, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureLike(String value) {
            addCriterion("equipmentPicture like", value, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureNotLike(String value) {
            addCriterion("equipmentPicture not like", value, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureIn(List<String> values) {
            addCriterion("equipmentPicture in", values, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureNotIn(List<String> values) {
            addCriterion("equipmentPicture not in", values, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureBetween(String value1, String value2) {
            addCriterion("equipmentPicture between", value1, value2, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentpictureNotBetween(String value1, String value2) {
            addCriterion("equipmentPicture not between", value1, value2, "equipmentpicture");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameIsNull() {
            addCriterion("equipmentName is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameIsNotNull() {
            addCriterion("equipmentName is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameEqualTo(String value) {
            addCriterion("equipmentName =", value, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameNotEqualTo(String value) {
            addCriterion("equipmentName <>", value, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameGreaterThan(String value) {
            addCriterion("equipmentName >", value, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameGreaterThanOrEqualTo(String value) {
            addCriterion("equipmentName >=", value, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameLessThan(String value) {
            addCriterion("equipmentName <", value, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameLessThanOrEqualTo(String value) {
            addCriterion("equipmentName <=", value, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameLike(String value) {
            addCriterion("equipmentName like", value, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameNotLike(String value) {
            addCriterion("equipmentName not like", value, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameIn(List<String> values) {
            addCriterion("equipmentName in", values, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameNotIn(List<String> values) {
            addCriterion("equipmentName not in", values, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameBetween(String value1, String value2) {
            addCriterion("equipmentName between", value1, value2, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andEquipmentnameNotBetween(String value1, String value2) {
            addCriterion("equipmentName not between", value1, value2, "equipmentname");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andBindedAtIsNull() {
            addCriterion("binded_at is null");
            return (Criteria) this;
        }

        public Criteria andBindedAtIsNotNull() {
            addCriterion("binded_at is not null");
            return (Criteria) this;
        }

        public Criteria andBindedAtEqualTo(Date value) {
            addCriterion("binded_at =", value, "bindedAt");
            return (Criteria) this;
        }

        public Criteria andBindedAtNotEqualTo(Date value) {
            addCriterion("binded_at <>", value, "bindedAt");
            return (Criteria) this;
        }

        public Criteria andBindedAtGreaterThan(Date value) {
            addCriterion("binded_at >", value, "bindedAt");
            return (Criteria) this;
        }

        public Criteria andBindedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("binded_at >=", value, "bindedAt");
            return (Criteria) this;
        }

        public Criteria andBindedAtLessThan(Date value) {
            addCriterion("binded_at <", value, "bindedAt");
            return (Criteria) this;
        }

        public Criteria andBindedAtLessThanOrEqualTo(Date value) {
            addCriterion("binded_at <=", value, "bindedAt");
            return (Criteria) this;
        }

        public Criteria andBindedAtIn(List<Date> values) {
            addCriterion("binded_at in", values, "bindedAt");
            return (Criteria) this;
        }

        public Criteria andBindedAtNotIn(List<Date> values) {
            addCriterion("binded_at not in", values, "bindedAt");
            return (Criteria) this;
        }

        public Criteria andBindedAtBetween(Date value1, Date value2) {
            addCriterion("binded_at between", value1, value2, "bindedAt");
            return (Criteria) this;
        }

        public Criteria andBindedAtNotBetween(Date value1, Date value2) {
            addCriterion("binded_at not between", value1, value2, "bindedAt");
            return (Criteria) this;
        }

        public Criteria andProductIsNull() {
            addCriterion("product is null");
            return (Criteria) this;
        }

        public Criteria andProductIsNotNull() {
            addCriterion("product is not null");
            return (Criteria) this;
        }

        public Criteria andProductEqualTo(String value) {
            addCriterion("product =", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotEqualTo(String value) {
            addCriterion("product <>", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductGreaterThan(String value) {
            addCriterion("product >", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductGreaterThanOrEqualTo(String value) {
            addCriterion("product >=", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductLessThan(String value) {
            addCriterion("product <", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductLessThanOrEqualTo(String value) {
            addCriterion("product <=", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductLike(String value) {
            addCriterion("product like", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotLike(String value) {
            addCriterion("product not like", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductIn(List<String> values) {
            addCriterion("product in", values, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotIn(List<String> values) {
            addCriterion("product not in", values, "product");
            return (Criteria) this;
        }

        public Criteria andProductBetween(String value1, String value2) {
            addCriterion("product between", value1, value2, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotBetween(String value1, String value2) {
            addCriterion("product not between", value1, value2, "product");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_equipment
     *
     * @mbggenerated do_not_delete_during_merge Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_equipment
     *
     * @mbggenerated Sat Oct 14 13:45:33 GMT+08:00 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}