package com.ontheroad.entity;

import java.util.Date;

public class TbNewsinformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newsinformation.id
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newsinformation.title
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newsinformation.createTime
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newsinformation.summary
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newsinformation.picture
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newsinformation.address
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newsinformation.status
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newsinformation.type
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newsinformation.content
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newsinformation.id
     *
     * @return the value of tb_newsinformation.id
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newsinformation.id
     *
     * @param id the value for tb_newsinformation.id
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newsinformation.title
     *
     * @return the value of tb_newsinformation.title
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newsinformation.title
     *
     * @param title the value for tb_newsinformation.title
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newsinformation.createTime
     *
     * @return the value of tb_newsinformation.createTime
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newsinformation.createTime
     *
     * @param createtime the value for tb_newsinformation.createTime
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newsinformation.summary
     *
     * @return the value of tb_newsinformation.summary
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newsinformation.summary
     *
     * @param summary the value for tb_newsinformation.summary
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newsinformation.picture
     *
     * @return the value of tb_newsinformation.picture
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newsinformation.picture
     *
     * @param picture the value for tb_newsinformation.picture
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newsinformation.address
     *
     * @return the value of tb_newsinformation.address
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newsinformation.address
     *
     * @param address the value for tb_newsinformation.address
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newsinformation.status
     *
     * @return the value of tb_newsinformation.status
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newsinformation.status
     *
     * @param status the value for tb_newsinformation.status
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newsinformation.type
     *
     * @return the value of tb_newsinformation.type
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newsinformation.type
     *
     * @param type the value for tb_newsinformation.type
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newsinformation.content
     *
     * @return the value of tb_newsinformation.content
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newsinformation.content
     *
     * @param content the value for tb_newsinformation.content
     *
     * @mbggenerated Thu Oct 19 17:04:00 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}