package com.ontheroad.mysql.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeviceWaterExample implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public DeviceWaterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Long value) {
            addCriterion("device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Long value) {
            addCriterion("device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Long value) {
            addCriterion("device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Long value) {
            addCriterion("device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Long value) {
            addCriterion("device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Long> values) {
            addCriterion("device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Long> values) {
            addCriterion("device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Long value1, Long value2) {
            addCriterion("device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Long value1, Long value2) {
            addCriterion("device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andUseWaterIsNull() {
            addCriterion("use_water is null");
            return (Criteria) this;
        }

        public Criteria andUseWaterIsNotNull() {
            addCriterion("use_water is not null");
            return (Criteria) this;
        }

        public Criteria andUseWaterEqualTo(String value) {
            addCriterion("use_water =", value, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterNotEqualTo(String value) {
            addCriterion("use_water <>", value, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterGreaterThan(String value) {
            addCriterion("use_water >", value, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterGreaterThanOrEqualTo(String value) {
            addCriterion("use_water >=", value, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterLessThan(String value) {
            addCriterion("use_water <", value, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterLessThanOrEqualTo(String value) {
            addCriterion("use_water <=", value, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterLike(String value) {
            addCriterion("use_water like", value, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterNotLike(String value) {
            addCriterion("use_water not like", value, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterIn(List<String> values) {
            addCriterion("use_water in", values, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterNotIn(List<String> values) {
            addCriterion("use_water not in", values, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterBetween(String value1, String value2) {
            addCriterion("use_water between", value1, value2, "useWater");
            return (Criteria) this;
        }

        public Criteria andUseWaterNotBetween(String value1, String value2) {
            addCriterion("use_water not between", value1, value2, "useWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterIsNull() {
            addCriterion("jie_water is null");
            return (Criteria) this;
        }

        public Criteria andJieWaterIsNotNull() {
            addCriterion("jie_water is not null");
            return (Criteria) this;
        }

        public Criteria andJieWaterEqualTo(String value) {
            addCriterion("jie_water =", value, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterNotEqualTo(String value) {
            addCriterion("jie_water <>", value, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterGreaterThan(String value) {
            addCriterion("jie_water >", value, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterGreaterThanOrEqualTo(String value) {
            addCriterion("jie_water >=", value, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterLessThan(String value) {
            addCriterion("jie_water <", value, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterLessThanOrEqualTo(String value) {
            addCriterion("jie_water <=", value, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterLike(String value) {
            addCriterion("jie_water like", value, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterNotLike(String value) {
            addCriterion("jie_water not like", value, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterIn(List<String> values) {
            addCriterion("jie_water in", values, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterNotIn(List<String> values) {
            addCriterion("jie_water not in", values, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterBetween(String value1, String value2) {
            addCriterion("jie_water between", value1, value2, "jieWater");
            return (Criteria) this;
        }

        public Criteria andJieWaterNotBetween(String value1, String value2) {
            addCriterion("jie_water not between", value1, value2, "jieWater");
            return (Criteria) this;
        }

        public Criteria andBathTimeIsNull() {
            addCriterion("bath_time is null");
            return (Criteria) this;
        }

        public Criteria andBathTimeIsNotNull() {
            addCriterion("bath_time is not null");
            return (Criteria) this;
        }

        public Criteria andBathTimeEqualTo(String value) {
            addCriterion("bath_time =", value, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeNotEqualTo(String value) {
            addCriterion("bath_time <>", value, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeGreaterThan(String value) {
            addCriterion("bath_time >", value, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeGreaterThanOrEqualTo(String value) {
            addCriterion("bath_time >=", value, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeLessThan(String value) {
            addCriterion("bath_time <", value, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeLessThanOrEqualTo(String value) {
            addCriterion("bath_time <=", value, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeLike(String value) {
            addCriterion("bath_time like", value, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeNotLike(String value) {
            addCriterion("bath_time not like", value, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeIn(List<String> values) {
            addCriterion("bath_time in", values, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeNotIn(List<String> values) {
            addCriterion("bath_time not in", values, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeBetween(String value1, String value2) {
            addCriterion("bath_time between", value1, value2, "bathTime");
            return (Criteria) this;
        }

        public Criteria andBathTimeNotBetween(String value1, String value2) {
            addCriterion("bath_time not between", value1, value2, "bathTime");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureIsNull() {
            addCriterion("set_temperature is null");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureIsNotNull() {
            addCriterion("set_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureEqualTo(String value) {
            addCriterion("set_temperature =", value, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureNotEqualTo(String value) {
            addCriterion("set_temperature <>", value, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureGreaterThan(String value) {
            addCriterion("set_temperature >", value, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureGreaterThanOrEqualTo(String value) {
            addCriterion("set_temperature >=", value, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureLessThan(String value) {
            addCriterion("set_temperature <", value, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureLessThanOrEqualTo(String value) {
            addCriterion("set_temperature <=", value, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureLike(String value) {
            addCriterion("set_temperature like", value, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureNotLike(String value) {
            addCriterion("set_temperature not like", value, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureIn(List<String> values) {
            addCriterion("set_temperature in", values, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureNotIn(List<String> values) {
            addCriterion("set_temperature not in", values, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureBetween(String value1, String value2) {
            addCriterion("set_temperature between", value1, value2, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andSetTemperatureNotBetween(String value1, String value2) {
            addCriterion("set_temperature not between", value1, value2, "setTemperature");
            return (Criteria) this;
        }

        public Criteria andFlowGradeIsNull() {
            addCriterion("flow_grade is null");
            return (Criteria) this;
        }

        public Criteria andFlowGradeIsNotNull() {
            addCriterion("flow_grade is not null");
            return (Criteria) this;
        }

        public Criteria andFlowGradeEqualTo(String value) {
            addCriterion("flow_grade =", value, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeNotEqualTo(String value) {
            addCriterion("flow_grade <>", value, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeGreaterThan(String value) {
            addCriterion("flow_grade >", value, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeGreaterThanOrEqualTo(String value) {
            addCriterion("flow_grade >=", value, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeLessThan(String value) {
            addCriterion("flow_grade <", value, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeLessThanOrEqualTo(String value) {
            addCriterion("flow_grade <=", value, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeLike(String value) {
            addCriterion("flow_grade like", value, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeNotLike(String value) {
            addCriterion("flow_grade not like", value, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeIn(List<String> values) {
            addCriterion("flow_grade in", values, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeNotIn(List<String> values) {
            addCriterion("flow_grade not in", values, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeBetween(String value1, String value2) {
            addCriterion("flow_grade between", value1, value2, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andFlowGradeNotBetween(String value1, String value2) {
            addCriterion("flow_grade not between", value1, value2, "flowGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(String value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(String value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(String value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(String value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(String value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(String value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLike(String value) {
            addCriterion("grade like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotLike(String value) {
            addCriterion("grade not like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<String> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<String> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(String value1, String value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(String value1, String value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_water
     *
     * @mbggenerated do_not_delete_during_merge Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria implements Serializable{

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public static class Criterion implements Serializable{
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}