package com.ontheroad.mysql.entity;

import java.io.Serializable;
import java.util.Date;

public class DeviceWater implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_water.id
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_water.device_id
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    private Long deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_water.use_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    private String useWater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_water.jie_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    private String jieWater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_water.bath_time
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    private String bathTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_water.set_temperature
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    private String setTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_water.flow_grade
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    private String flowGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_water.grade
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_water.create_time
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_water.id
     *
     * @return the value of device_water.id
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_water.id
     *
     * @param id the value for device_water.id
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_water.device_id
     *
     * @return the value of device_water.device_id
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_water.device_id
     *
     * @param deviceId the value for device_water.device_id
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_water.use_water
     *
     * @return the value of device_water.use_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public String getUseWater() {
        return useWater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_water.use_water
     *
     * @param useWater the value for device_water.use_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setUseWater(String useWater) {
        this.useWater = useWater == null ? null : useWater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_water.jie_water
     *
     * @return the value of device_water.jie_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public String getJieWater() {
        return jieWater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_water.jie_water
     *
     * @param jieWater the value for device_water.jie_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setJieWater(String jieWater) {
        this.jieWater = jieWater == null ? null : jieWater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_water.bath_time
     *
     * @return the value of device_water.bath_time
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public String getBathTime() {
        return bathTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_water.bath_time
     *
     * @param bathTime the value for device_water.bath_time
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setBathTime(String bathTime) {
        this.bathTime = bathTime == null ? null : bathTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_water.set_temperature
     *
     * @return the value of device_water.set_temperature
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public String getSetTemperature() {
        return setTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_water.set_temperature
     *
     * @param setTemperature the value for device_water.set_temperature
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setSetTemperature(String setTemperature) {
        this.setTemperature = setTemperature == null ? null : setTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_water.flow_grade
     *
     * @return the value of device_water.flow_grade
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public String getFlowGrade() {
        return flowGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_water.flow_grade
     *
     * @param flowGrade the value for device_water.flow_grade
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setFlowGrade(String flowGrade) {
        this.flowGrade = flowGrade == null ? null : flowGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_water.grade
     *
     * @return the value of device_water.grade
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_water.grade
     *
     * @param grade the value for device_water.grade
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_water.create_time
     *
     * @return the value of device_water.create_time
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_water.create_time
     *
     * @param createTime the value for device_water.create_time
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}