package com.ontheroad.mysql.entity;

import java.util.Date;

public class GuaranteeType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_type.id
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_type.device_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    private String deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_type.type_name
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_type.create_time
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_type.motify_time
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    private Date motifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_type.id
     *
     * @return the value of guarantee_type.id
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_type.id
     *
     * @param id the value for guarantee_type.id
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_type.device_type
     *
     * @return the value of guarantee_type.device_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_type.device_type
     *
     * @param deviceType the value for guarantee_type.device_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_type.type_name
     *
     * @return the value of guarantee_type.type_name
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_type.type_name
     *
     * @param typeName the value for guarantee_type.type_name
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_type.create_time
     *
     * @return the value of guarantee_type.create_time
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_type.create_time
     *
     * @param createTime the value for guarantee_type.create_time
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_type.motify_time
     *
     * @return the value of guarantee_type.motify_time
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    public Date getMotifyTime() {
        return motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_type.motify_time
     *
     * @param motifyTime the value for guarantee_type.motify_time
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    public void setMotifyTime(Date motifyTime) {
        this.motifyTime = motifyTime;
    }
}