package com.ontheroad.mysql.entity;

import java.util.Date;

public class TbCustomerservicedetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customerservicedetails.serviceDetail_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    private Integer servicedetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customerservicedetails.equipment_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    private Integer equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customerservicedetails.user_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customerservicedetails.time
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customerservicedetails.personName
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    private String personname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customerservicedetails.personPhone
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    private String personphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customerservicedetails.content
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customerservicedetails.log_type
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    private Long logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customerservicedetails.customer_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    private Long customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customerservicedetails.serviceDetail_id
     *
     * @return the value of tb_customerservicedetails.serviceDetail_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public Integer getServicedetailId() {
        return servicedetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customerservicedetails.serviceDetail_id
     *
     * @param servicedetailId the value for tb_customerservicedetails.serviceDetail_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public void setServicedetailId(Integer servicedetailId) {
        this.servicedetailId = servicedetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customerservicedetails.equipment_id
     *
     * @return the value of tb_customerservicedetails.equipment_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public Integer getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customerservicedetails.equipment_id
     *
     * @param equipmentId the value for tb_customerservicedetails.equipment_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public void setEquipmentId(Integer equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customerservicedetails.user_id
     *
     * @return the value of tb_customerservicedetails.user_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customerservicedetails.user_id
     *
     * @param userId the value for tb_customerservicedetails.user_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customerservicedetails.time
     *
     * @return the value of tb_customerservicedetails.time
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customerservicedetails.time
     *
     * @param time the value for tb_customerservicedetails.time
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customerservicedetails.personName
     *
     * @return the value of tb_customerservicedetails.personName
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public String getPersonname() {
        return personname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customerservicedetails.personName
     *
     * @param personname the value for tb_customerservicedetails.personName
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public void setPersonname(String personname) {
        this.personname = personname == null ? null : personname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customerservicedetails.personPhone
     *
     * @return the value of tb_customerservicedetails.personPhone
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public String getPersonphone() {
        return personphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customerservicedetails.personPhone
     *
     * @param personphone the value for tb_customerservicedetails.personPhone
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public void setPersonphone(String personphone) {
        this.personphone = personphone == null ? null : personphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customerservicedetails.content
     *
     * @return the value of tb_customerservicedetails.content
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customerservicedetails.content
     *
     * @param content the value for tb_customerservicedetails.content
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customerservicedetails.log_type
     *
     * @return the value of tb_customerservicedetails.log_type
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public Long getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customerservicedetails.log_type
     *
     * @param logType the value for tb_customerservicedetails.log_type
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public void setLogType(Long logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customerservicedetails.customer_id
     *
     * @return the value of tb_customerservicedetails.customer_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customerservicedetails.customer_id
     *
     * @param customerId the value for tb_customerservicedetails.customer_id
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
}