package com.ontheroad.mysql.dao;

import com.ontheroad.mysql.entity.DeviceUseLog;
import com.ontheroad.mysql.entity.DeviceUseLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceUseLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    int countByExample(DeviceUseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    int deleteByExample(DeviceUseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    int insert(DeviceUseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    int insertSelective(DeviceUseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    List<DeviceUseLog> selectByExample(DeviceUseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    DeviceUseLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") DeviceUseLog record, @Param("example") DeviceUseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    int updateByExample(@Param("record") DeviceUseLog record, @Param("example") DeviceUseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(DeviceUseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_use_log
     *
     * @mbggenerated Fri Oct 20 21:55:42 GMT+08:00 2017
     */
    int updateByPrimaryKey(DeviceUseLog record);
}