package com.ontheroad.mysql.dao;

import com.ontheroad.mysql.entity.DeviceWater;
import com.ontheroad.mysql.entity.DeviceWaterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceWaterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    int countByExample(DeviceWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    int deleteByExample(DeviceWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    int insert(DeviceWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    int insertSelective(DeviceWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    List<DeviceWater> selectByExample(DeviceWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    DeviceWater selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") DeviceWater record, @Param("example") DeviceWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    int updateByExample(@Param("record") DeviceWater record, @Param("example") DeviceWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(DeviceWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_water
     *
     * @mbggenerated Fri Oct 20 22:36:01 GMT+08:00 2017
     */
    int updateByPrimaryKey(DeviceWater record);
}