package com.ontheroad.mysql.dao;

import com.ontheroad.mysql.entity.GuaranteeType;
import com.ontheroad.mysql.entity.GuaranteeTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuaranteeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    int countByExample(GuaranteeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    int deleteByExample(GuaranteeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    int insert(GuaranteeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    int insertSelective(GuaranteeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    List<GuaranteeType> selectByExample(GuaranteeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    GuaranteeType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") GuaranteeType record, @Param("example") GuaranteeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    int updateByExample(@Param("record") GuaranteeType record, @Param("example") GuaranteeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    int updateByPrimaryKeySelective(GuaranteeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_type
     *
     * @mbggenerated Sat Oct 28 14:33:11 CST 2017
     */
    int updateByPrimaryKey(GuaranteeType record);
}