package com.ontheroad.mysql.dao;

import com.ontheroad.mysql.entity.TbCustomerservicedetails;
import com.ontheroad.mysql.entity.TbCustomerservicedetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCustomerservicedetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    int countByExample(TbCustomerservicedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    int deleteByExample(TbCustomerservicedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    int deleteByPrimaryKey(Integer servicedetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    int insert(TbCustomerservicedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    int insertSelective(TbCustomerservicedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    List<TbCustomerservicedetails> selectByExample(TbCustomerservicedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    TbCustomerservicedetails selectByPrimaryKey(Integer servicedetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbCustomerservicedetails record, @Param("example") TbCustomerservicedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    int updateByExample(@Param("record") TbCustomerservicedetails record, @Param("example") TbCustomerservicedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    int updateByPrimaryKeySelective(TbCustomerservicedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customerservicedetails
     *
     * @mbggenerated Sat Oct 28 14:11:32 CST 2017
     */
    int updateByPrimaryKey(TbCustomerservicedetails record);
}