package com.ontheroad.mysql.dao;

import com.ontheroad.mysql.entity.TbGuarantee;
import com.ontheroad.mysql.entity.TbGuaranteeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbGuaranteeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    int countByExample(TbGuaranteeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    int deleteByExample(TbGuaranteeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    int deleteByPrimaryKey(Integer guaranteeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    int insert(TbGuarantee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    int insertSelective(TbGuarantee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    List<TbGuarantee> selectByExample(TbGuaranteeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    TbGuarantee selectByPrimaryKey(Integer guaranteeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbGuarantee record, @Param("example") TbGuaranteeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    int updateByExample(@Param("record") TbGuarantee record, @Param("example") TbGuaranteeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    int updateByPrimaryKeySelective(TbGuarantee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guarantee
     *
     * @mbggenerated Sun Oct 29 09:24:55 CST 2017
     */
    int updateByPrimaryKey(TbGuarantee record);
}